package com.example.taras.core.tcg.seed

import com.example.taras.core.db.tcg.TcgCardEntity
import com.example.taras.core.tcg.model.CardMove
import com.example.taras.core.tcg.model.CardRole
import com.example.taras.core.tcg.model.EnergyType
import com.example.taras.core.tcg.model.RarityTier
import com.example.taras.core.tcg.model.TelemetryRadarStats

object RosterSeedData {

    val allCards: List<TcgCardEntity> = listOf(
        TcgCardEntity(
            id = "card_fer_44",
            cardNumber = 1,
            name = "Lewis Hamilton",
            code = "HAM",
            driverNumber = "#44",
            teamId = "ferrari",
            teamName = "Scuderia Ferrari HP",
            primaryColorHex = "#E8002D",
            secondaryColorHex = "#FFE500",
            tier = RarityTier.S_TIER,
            ovr = 99,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2007",
            nationality = "United Kingdom",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/ferrari/lewham01/2026ferrarilewham01right.webp",
            verticalBannerText = "HAMILTON",
            move1 = CardMove(
                title = "Montmelo Pace Strike",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 98,
                description = "Late-apex throttle commitment down the start-finish straight. Generates +10 Pace points in clean air."
            ),
            move2 = CardMove(
                title = "Maranello Hammer Time",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 99,
                description = "Flawless qualifying pace lap with sector 3 purple speed traps. Opponent loses tyre life next turn."
            ),
            weaknessText = "Safety Car Strategy x 2",
            resistanceText = "Tyre Deg -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 99, racecraft = 99, tyreManagement = 98, wetSkill = 99, consistency = 98)
        ),
        TcgCardEntity(
            id = "card_fer_16",
            cardNumber = 2,
            name = "Charles Leclerc",
            code = "LEC",
            driverNumber = "#16",
            teamId = "ferrari",
            teamName = "Scuderia Ferrari HP",
            primaryColorHex = "#E8002D",
            secondaryColorHex = "#FFE500",
            tier = RarityTier.S_TIER,
            ovr = 95,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2018",
            nationality = "Monaco",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/ferrari/chalec01/2026ferrarichalec01right.webp",
            verticalBannerText = "LECLERC",
            move1 = CardMove(
                title = "Sakhir Qualifying Sweep",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.PACE),
                power = 97,
                description = "Precision low-fuel pole position sprint across traction zones with unmatched one-lap pace."
            ),
            move2 = CardMove(
                title = "Apex Oversteer Snap",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 95,
                description = "High-speed mid-corner rotation dancing over kerbs to steal the inside racing line."
            ),
            weaknessText = "Strategy Blunder x 2",
            resistanceText = "Clean Air -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 98, racecraft = 92, tyreManagement = 89, wetSkill = 91, consistency = 92)
        ),
        TcgCardEntity(
            id = "card_mcl_01",
            cardNumber = 3,
            name = "Lando Norris",
            code = "NOR",
            driverNumber = "#1",
            teamId = "mclaren",
            teamName = "McLaren Formula 1 Team",
            primaryColorHex = "#FF8000",
            secondaryColorHex = "#47C7FC",
            tier = RarityTier.S_TIER,
            ovr = 97,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2019",
            nationality = "United Kingdom",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/mclaren/lannor01/2026mclarenlannor01right.webp",
            verticalBannerText = "NORRIS",
            move1 = CardMove(
                title = "Papaya Low-Fuel Sprint",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.PACE),
                power = 96,
                description = "Extreme minimum apex speed through sector 2, carving 0.3s off the benchmark telemetry time."
            ),
            move2 = CardMove(
                title = "Woking Turbo Boost",
                energyCosts = listOf(EnergyType.PACE, EnergyType.RACECRAFT),
                power = 98,
                description = "Full battery deployment across DRS activation zones to execute an unstoppably clean overtake."
            ),
            weaknessText = "Wet Standing Water x 2",
            resistanceText = "Medium Corners -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 97, racecraft = 95, tyreManagement = 93, wetSkill = 91, consistency = 94)
        ),
        TcgCardEntity(
            id = "card_mcl_81",
            cardNumber = 4,
            name = "Oscar Piastri",
            code = "PIA",
            driverNumber = "#81",
            teamId = "mclaren",
            teamName = "McLaren Formula 1 Team",
            primaryColorHex = "#FF8000",
            secondaryColorHex = "#47C7FC",
            tier = RarityTier.A_TIER,
            ovr = 94,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2023",
            nationality = "Australia",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/mclaren/oscpia01/2026mclarenoscpia01right.webp",
            verticalBannerText = "PIASTRI",
            move1 = CardMove(
                title = "Ice-Cold Turn 1 Lunge",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 93,
                description = "Unshakable late braking down the inside line, maintaining track limits without tyre lockup."
            ),
            move2 = CardMove(
                title = "Melbourne Sprint Surge",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 94,
                description = "Clinically smooth throttle modulation through consecutive chicane entries."
            ),
            weaknessText = "Rear Degradation x 2",
            resistanceText = "High Speed -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 94, racecraft = 94, tyreManagement = 90, wetSkill = 89, consistency = 93)
        ),
        TcgCardEntity(
            id = "card_rbr_03",
            cardNumber = 5,
            name = "Max Verstappen",
            code = "VER",
            driverNumber = "#3",
            teamId = "redbull",
            teamName = "Oracle Red Bull Racing",
            primaryColorHex = "#3671C6",
            secondaryColorHex = "#EA1D2D",
            tier = RarityTier.S_TIER,
            ovr = 98,
            role = CardRole.DRIVER,
            powertrain = "Red Bull Powertrains",
            debutYear = "2015",
            nationality = "Netherlands",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/redbullracing/maxver01/2026redbullracingmaxver01right.webp",
            verticalBannerText = "VERSTAPPEN",
            move1 = CardMove(
                title = "Red Bull Divebomb",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 98,
                description = "Ferocious 100m brake marker attack on the apex, shutting the door on counter-attacks."
            ),
            move2 = CardMove(
                title = "Total Race Domination",
                energyCosts = listOf(EnergyType.PACE, EnergyType.DEFENSE),
                power = 99,
                description = "Metronomic 0.1s delta precision across 40 race laps, pulling a 20-second pit window gap."
            ),
            weaknessText = "Kerb Strike Shock x 2",
            resistanceText = "Wet Skill -30",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 99, racecraft = 99, tyreManagement = 96, wetSkill = 99, consistency = 97)
        ),
        TcgCardEntity(
            id = "card_rbr_06",
            cardNumber = 6,
            name = "Isack Hadjar",
            code = "HAD",
            driverNumber = "#6",
            teamId = "redbull",
            teamName = "Oracle Red Bull Racing",
            primaryColorHex = "#3671C6",
            secondaryColorHex = "#EA1D2D",
            tier = RarityTier.C_TIER,
            ovr = 82,
            role = CardRole.DRIVER,
            powertrain = "Red Bull Powertrains",
            debutYear = "2026",
            nationality = "France",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/redbullracing/isahad01/2026redbullracingisahad01right.webp",
            verticalBannerText = "HADJAR",
            move1 = CardMove(
                title = "Junior Academy Rush",
                energyCosts = listOf(EnergyType.PACE),
                power = 81,
                description = "Aggressive feeder-series attack lines demonstrating high bravery through blind sweepers."
            ),
            move2 = CardMove(
                title = "Milton Keynes Slipstream",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 83,
                description = "Tucking tight into aerodynamic wake to gain top-speed DRS advantage."
            ),
            weaknessText = "Track Limits Penalty x 2",
            resistanceText = "Straightline -10",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 83, racecraft = 82, tyreManagement = 80, wetSkill = 81, consistency = 79)
        ),
        TcgCardEntity(
            id = "card_mer_63",
            cardNumber = 7,
            name = "George Russell",
            code = "RUS",
            driverNumber = "#63",
            teamId = "mercedes",
            teamName = "Mercedes-AMG PETRONAS F1 Team",
            primaryColorHex = "#27F4D2",
            secondaryColorHex = "#FFFFFF",
            tier = RarityTier.S_TIER,
            ovr = 95,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2019",
            nationality = "United Kingdom",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/mercedes/georus01/2026mercedesgeorus01right.webp",
            verticalBannerText = "RUSSELL",
            move1 = CardMove(
                title = "Silver Arrow Qualifier",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.PACE),
                power = 96,
                description = "Pinpoint telemetry execution on the ragged edge, locking front-row grid priority."
            ),
            move2 = CardMove(
                title = "Braking Point Mastery",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.DEFENSE),
                power = 94,
                description = "Calculated positioning across high-G deceleration zones defending against DRS lunges."
            ),
            weaknessText = "Tyre Lockup x 2",
            resistanceText = "Clean Air -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 96, racecraft = 94, tyreManagement = 93, wetSkill = 92, consistency = 94)
        ),
        TcgCardEntity(
            id = "card_mer_12",
            cardNumber = 8,
            name = "Andrea Kimi Antonelli",
            code = "ANT",
            driverNumber = "#12",
            teamId = "mercedes",
            teamName = "Mercedes-AMG PETRONAS F1 Team",
            primaryColorHex = "#27F4D2",
            secondaryColorHex = "#FFFFFF",
            tier = RarityTier.A_TIER,
            ovr = 92,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2025",
            nationality = "Italy",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/mercedes/andant01/2026mercedesandant01right.webp",
            verticalBannerText = "ANTONELLI",
            move1 = CardMove(
                title = "Bologna Prodigy Launch",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 92,
                description = "Sensational high-speed reaction time off the starting grid, vaulting positions into Turn 1."
            ),
            move2 = CardMove(
                title = "Telemetry Precision",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.AERO),
                power = 91,
                description = "Near-telepathic throttle feathering keeping aerodynamic flow attached through corners."
            ),
            weaknessText = "Cold Tyre Graining x 2",
            resistanceText = "Rapid Transitions -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 94, racecraft = 91, tyreManagement = 88, wetSkill = 90, consistency = 90)
        ),
        TcgCardEntity(
            id = "card_amr_14",
            cardNumber = 9,
            name = "Fernando Alonso",
            code = "ALO",
            driverNumber = "#14",
            teamId = "astonmartin",
            teamName = "Aston Martin Aramco F1 Team",
            primaryColorHex = "#229971",
            secondaryColorHex = "#CEDC00",
            tier = RarityTier.A_TIER,
            ovr = 93,
            role = CardRole.DRIVER,
            powertrain = "Honda RA626H",
            debutYear = "2001",
            nationality = "Spain",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/astonmartin/feralo01/2026astonmartinferalo01right.webp",
            verticalBannerText = "ALONSO",
            move1 = CardMove(
                title = "El Nano Iron Defense",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.DEFENSE),
                power = 95,
                description = "Impenetrable masterclass placing the car perfectly to stall faster rival DRS trains."
            ),
            move2 = CardMove(
                title = "Asturian Rain Dance",
                energyCosts = listOf(EnergyType.PACE, EnergyType.RACECRAFT),
                power = 92,
                description = "Finding unconventional rubber grip on drenched track surfaces during changing weather."
            ),
            weaknessText = "Straightline Deficit x 2",
            resistanceText = "Tyre Preservation -25",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 92, racecraft = 98, tyreManagement = 97, wetSkill = 95, consistency = 96)
        ),
        TcgCardEntity(
            id = "card_amr_18",
            cardNumber = 10,
            name = "Lance Stroll",
            code = "STR",
            driverNumber = "#18",
            teamId = "astonmartin",
            teamName = "Aston Martin Aramco F1 Team",
            primaryColorHex = "#229971",
            secondaryColorHex = "#CEDC00",
            tier = RarityTier.C_TIER,
            ovr = 78,
            role = CardRole.DRIVER,
            powertrain = "Honda RA626H",
            debutYear = "2017",
            nationality = "Canada",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/astonmartin/lanstr01/2026astonmartinlanstr01right.webp",
            verticalBannerText = "STROLL",
            move1 = CardMove(
                title = "Opening Lap Hustle",
                energyCosts = listOf(EnergyType.RACECRAFT),
                power = 79,
                description = "Aggressive first-lap lane picks finding gaps along the outside perimeter."
            ),
            move2 = CardMove(
                title = "Wet Weather Blitz",
                energyCosts = listOf(EnergyType.PACE, EnergyType.DEFENSE),
                power = 80,
                description = "Brave early switch to intermediate tyres jumping opponents during torrential showers."
            ),
            weaknessText = "Sector 3 Delta x 2",
            resistanceText = "Wet Grip -10",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 78, racecraft = 81, tyreManagement = 77, wetSkill = 82, consistency = 76)
        ),
        TcgCardEntity(
            id = "card_alp_10",
            cardNumber = 11,
            name = "Pierre Gasly",
            code = "GAS",
            driverNumber = "#10",
            teamId = "alpine",
            teamName = "BWT Alpine F1 Team",
            primaryColorHex = "#00A1E8",
            secondaryColorHex = "#FF87BC",
            tier = RarityTier.B_TIER,
            ovr = 86,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2017",
            nationality = "France",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/alpine/piegas01/2026alpinepiegas01right.webp",
            verticalBannerText = "GASLY",
            move1 = CardMove(
                title = "Monza Apex Flick",
                energyCosts = listOf(EnergyType.PACE, EnergyType.RACECRAFT),
                power = 87,
                description = "High-commitment chicane clipping taking curbs aggressively to preserve exit momentum."
            ),
            move2 = CardMove(
                title = "Midfield Under-Cut",
                energyCosts = listOf(EnergyType.DEFENSE, EnergyType.PACE),
                power = 85,
                description = "Punchy in-lap on fresh rubber jumping two positions through the pit-stop sequence."
            ),
            weaknessText = "Engine Derate x 2",
            resistanceText = "Slipstream Defend -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 87, racecraft = 86, tyreManagement = 85, wetSkill = 87, consistency = 86)
        ),
        TcgCardEntity(
            id = "card_alp_43",
            cardNumber = 12,
            name = "Franco Colapinto",
            code = "COL",
            driverNumber = "#43",
            teamId = "alpine",
            teamName = "BWT Alpine F1 Team",
            primaryColorHex = "#00A1E8",
            secondaryColorHex = "#FF87BC",
            tier = RarityTier.B_TIER,
            ovr = 83,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2024",
            nationality = "Argentina",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/alpine/fracol01/2026alpinefracol01right.webp",
            verticalBannerText = "COLAPINTO",
            move1 = CardMove(
                title = "Baku Castle Threader",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 84,
                description = "Incredible millimeter proximity against street-circuit concrete walls."
            ),
            move2 = CardMove(
                title = "Pampas Full Throttle",
                energyCosts = listOf(EnergyType.PACE),
                power = 82,
                description = "Fearless commitment through ultra high-speed sector 3 kinks."
            ),
            weaknessText = "Cold Tyre Snap x 2",
            resistanceText = "Street Braking -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 85, racecraft = 83, tyreManagement = 81, wetSkill = 80, consistency = 81)
        ),
        TcgCardEntity(
            id = "card_wil_55",
            cardNumber = 13,
            name = "Carlos Sainz Jr.",
            code = "SAI",
            driverNumber = "#55",
            teamId = "williams",
            teamName = "Williams Racing",
            primaryColorHex = "#1868DB",
            secondaryColorHex = "#00A3E0",
            tier = RarityTier.A_TIER,
            ovr = 91,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2015",
            nationality = "Spain",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/williams/carsai01/2026williamscarsai01right.webp",
            verticalBannerText = "SAINZ",
            move1 = CardMove(
                title = "Smooth Operator Ploy",
                energyCosts = listOf(EnergyType.DEFENSE, EnergyType.RACECRAFT),
                power = 92,
                description = "Genius tactical DRS towing providing trailing rivals wing buffer to freeze lead battles."
            ),
            move2 = CardMove(
                title = "Grove Power Sweep",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 90,
                description = "Relentless aerodynamic speed down the longest straights keeping clean track trackside."
            ),
            weaknessText = "Slow Pit Stop Delay x 2",
            resistanceText = "Race Craft Mastery -20",
            pitCost = 2,
            radarStats = TelemetryRadarStats(qualifyingPace = 91, racecraft = 93, tyreManagement = 92, wetSkill = 89, consistency = 93)
        ),
        TcgCardEntity(
            id = "card_wil_23",
            cardNumber = 14,
            name = "Alexander Albon",
            code = "ALB",
            driverNumber = "#23",
            teamId = "williams",
            teamName = "Williams Racing",
            primaryColorHex = "#1868DB",
            secondaryColorHex = "#00A3E0",
            tier = RarityTier.B_TIER,
            ovr = 87,
            role = CardRole.DRIVER,
            powertrain = "Mercedes-AMG M17",
            debutYear = "2019",
            nationality = "Thailand",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/williams/alealb01/2026williamsalealb01right.webp",
            verticalBannerText = "ALBON",
            move1 = CardMove(
                title = "Williams Straightline Rocket",
                energyCosts = listOf(EnergyType.PACE, EnergyType.AERO),
                power = 88,
                description = "Ultra low drag aero trim hitting top speed trap marks to lock out pursuing cars."
            ),
            move2 = CardMove(
                title = "Tyre Whisperer Stint",
                energyCosts = listOf(EnergyType.DEFENSE, EnergyType.PACE),
                power = 86,
                description = "Extending hard compound life across 50 laps without cliff degradation."
            ),
            weaknessText = "High Downforce Grip x 2",
            resistanceText = "Top Speed Shield -20",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 88, racecraft = 87, tyreManagement = 91, wetSkill = 84, consistency = 87)
        ),
        TcgCardEntity(
            id = "card_vcarb_30",
            cardNumber = 15,
            name = "Liam Lawson",
            code = "LAW",
            driverNumber = "#30",
            teamId = "racingbulls",
            teamName = "Visa Cash App RB F1 Team",
            primaryColorHex = "#6692FF",
            secondaryColorHex = "#FFFFFF",
            tier = RarityTier.B_TIER,
            ovr = 84,
            role = CardRole.DRIVER,
            powertrain = "Red Bull Powertrains",
            debutYear = "2023",
            nationality = "New Zealand",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/racingbulls/lialaw01/2026racingbullslialaw01right.webp",
            verticalBannerText = "LAWSON",
            move1 = CardMove(
                title = "Kiwi Wheel-to-Wheel Snap",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 85,
                description = "Refusing to yield in tight esses, hanging on the outside kerb to snatch the switchback."
            ),
            move2 = CardMove(
                title = "Faenza Rapid Attack",
                energyCosts = listOf(EnergyType.PACE),
                power = 83,
                description = "Quick-fire telemetry pace through short medium-speed radius corners."
            ),
            weaknessText = "Over-Aggressive Contact x 2",
            resistanceText = "Kerb Riding -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 85, racecraft = 86, tyreManagement = 82, wetSkill = 83, consistency = 83)
        ),
        TcgCardEntity(
            id = "card_vcarb_22",
            cardNumber = 16,
            name = "Yuki Tsunoda",
            code = "TSU",
            driverNumber = "#22",
            teamId = "racingbulls",
            teamName = "Visa Cash App RB F1 Team",
            primaryColorHex = "#6692FF",
            secondaryColorHex = "#FFFFFF",
            tier = RarityTier.B_TIER,
            ovr = 85,
            role = CardRole.DRIVER,
            powertrain = "Red Bull Powertrains",
            debutYear = "2021",
            nationality = "Japan",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/racingbulls/yuktsu01/2026racingbullsyuktsu01right.webp",
            verticalBannerText = "TSUNODA",
            move1 = CardMove(
                title = "Suzuka Degner Drift",
                energyCosts = listOf(EnergyType.PACE, EnergyType.RACECRAFT),
                power = 86,
                description = "Razor-sharp weight transfer through iconic S-curves with pinpoint front axle precision."
            ),
            move2 = CardMove(
                title = "Radio Rage Surge",
                energyCosts = listOf(EnergyType.PACE),
                power = 84,
                description = "Fiery adrenaline-fueled sector 1 attack cutting into rivals' gap."
            ),
            weaknessText = "Traffic Congestion x 2",
            resistanceText = "Low-Speed Agility -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 87, racecraft = 85, tyreManagement = 83, wetSkill = 84, consistency = 83)
        ),
        TcgCardEntity(
            id = "card_vcarb_41",
            cardNumber = 17,
            name = "Arvid Lindblad",
            code = "LIN",
            driverNumber = "#41",
            teamId = "racingbulls",
            teamName = "Visa Cash App RB F1 Team",
            primaryColorHex = "#6692FF",
            secondaryColorHex = "#FFFFFF",
            tier = RarityTier.C_TIER,
            ovr = 79,
            role = CardRole.DRIVER,
            powertrain = "Red Bull Powertrains",
            debutYear = "2026",
            nationality = "United Kingdom",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/racingbulls/arvlin01/2026racingbullsarvlin01right.webp",
            verticalBannerText = "LINDBLAD",
            move1 = CardMove(
                title = "Rookie Fearless Drift",
                energyCosts = listOf(EnergyType.PACE),
                power = 78,
                description = "Bold throttle applications exploring track grip limits."
            ),
            move2 = CardMove(
                title = "Red Bull Junior Sprint",
                energyCosts = listOf(EnergyType.RACECRAFT),
                power = 80,
                description = "Energetic overtaking manoeuvres catching midfield runners off guard."
            ),
            weaknessText = "Delta Consistency x 2",
            resistanceText = "Tyre Warmup -10",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 80, racecraft = 80, tyreManagement = 77, wetSkill = 78, consistency = 77)
        ),
        TcgCardEntity(
            id = "card_aud_27",
            cardNumber = 18,
            name = "Nico Hülkenberg",
            code = "HUL",
            driverNumber = "#27",
            teamId = "audi",
            teamName = "Audi Revolut F1 Team",
            primaryColorHex = "#FF2D00",
            secondaryColorHex = "#1A1A1A",
            tier = RarityTier.B_TIER,
            ovr = 86,
            role = CardRole.DRIVER,
            powertrain = "Audi Hybrid V6",
            debutYear = "2010",
            nationality = "Germany",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/audi/nichul01/2026audinichul01right.webp",
            verticalBannerText = "HULKENBERG",
            move1 = CardMove(
                title = "Hulk Q3 Wonder Lap",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.PACE),
                power = 88,
                description = "Dragging lower-midfield machinery straight into top 6 shootout qualifying positions."
            ),
            move2 = CardMove(
                title = "Ingolstadt Turbo Drive",
                energyCosts = listOf(EnergyType.PACE, EnergyType.DEFENSE),
                power = 85,
                description = "Efficient battery recovery and steady lap cadence defending track position."
            ),
            weaknessText = "Race Day Fade x 2",
            resistanceText = "One-Lap Spike -20",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 89, racecraft = 85, tyreManagement = 84, wetSkill = 85, consistency = 85)
        ),
        TcgCardEntity(
            id = "card_aud_05",
            cardNumber = 19,
            name = "Gabriel Bortoleto",
            code = "BOR",
            driverNumber = "#5",
            teamId = "audi",
            teamName = "Audi Revolut F1 Team",
            primaryColorHex = "#FF2D00",
            secondaryColorHex = "#1A1A1A",
            tier = RarityTier.C_TIER,
            ovr = 81,
            role = CardRole.DRIVER,
            powertrain = "Audi Hybrid V6",
            debutYear = "2026",
            nationality = "Brazil",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/audi/gabbor01/2026audigabbor01right.webp",
            verticalBannerText = "BORTOLETO",
            move1 = CardMove(
                title = "Paulista Rhythm",
                energyCosts = listOf(EnergyType.PACE),
                power = 80,
                description = "Flowing telemetry through fast linked turns balancing downforce."
            ),
            move2 = CardMove(
                title = "Audi Works Ascent",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 82,
                description = "Capitalizing on factory package developments during grand prix stints."
            ),
            weaknessText = "Pit Lane Entry x 2",
            resistanceText = "Braking Efficiency -10",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 82, racecraft = 81, tyreManagement = 80, wetSkill = 80, consistency = 80)
        ),
        TcgCardEntity(
            id = "card_cad_11",
            cardNumber = 20,
            name = "Sergio Pérez",
            code = "PER",
            driverNumber = "#11",
            teamId = "cadillac",
            teamName = "Cadillac F1 Team",
            primaryColorHex = "#8E9297",
            secondaryColorHex = "#CC0000",
            tier = RarityTier.B_TIER,
            ovr = 85,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2011",
            nationality = "Mexico",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/cadillac/serper01/2026cadillacserper01right.webp",
            verticalBannerText = "PEREZ",
            move1 = CardMove(
                title = "Minister of Defense",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.DEFENSE),
                power = 87,
                description = "Flawless positioning through braking zones denying rivals clean apex exits."
            ),
            move2 = CardMove(
                title = "Detroit Power Charge",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 84,
                description = "High torque drive out of slow hairpins to defend against DRS advances."
            ),
            weaknessText = "Saturday Q1 Delta x 2",
            resistanceText = "Tyre Preservation -20",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 81, racecraft = 89, tyreManagement = 90, wetSkill = 84, consistency = 84)
        ),
        TcgCardEntity(
            id = "card_cad_77",
            cardNumber = 21,
            name = "Valtteri Bottas",
            code = "BOT",
            driverNumber = "#77",
            teamId = "cadillac",
            teamName = "Cadillac F1 Team",
            primaryColorHex = "#8E9297",
            secondaryColorHex = "#CC0000",
            tier = RarityTier.B_TIER,
            ovr = 84,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2013",
            nationality = "Finland",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/cadillac/valbot01/2026cadillacvalbot01right.webp",
            verticalBannerText = "BOTTAS",
            move1 = CardMove(
                title = "Flying Finn Qualifying",
                energyCosts = listOf(EnergyType.QUALIFYING, EnergyType.PACE),
                power = 86,
                description = "Clinical, laser-guided speed on fresh soft tyres hitting every apex perfectly."
            ),
            move2 = CardMove(
                title = "V8 Thunder Strike",
                energyCosts = listOf(EnergyType.PACE),
                power = 83,
                description = "Solid straight-line pace down open stretches."
            ),
            weaknessText = "First Lap Pack Pinch x 2",
            resistanceText = "Clean Air Pace -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 86, racecraft = 82, tyreManagement = 85, wetSkill = 86, consistency = 84)
        ),
        TcgCardEntity(
            id = "card_has_31",
            cardNumber = 22,
            name = "Esteban Ocon",
            code = "OCO",
            driverNumber = "#31",
            teamId = "haas",
            teamName = "MoneyGram Haas F1 Team",
            primaryColorHex = "#DEE1E2",
            secondaryColorHex = "#E10600",
            tier = RarityTier.B_TIER,
            ovr = 85,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2016",
            nationality = "France",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/haas/estoco01/2026haasestoco01right.webp",
            verticalBannerText = "OCON",
            move1 = CardMove(
                title = "Hungaroring Lockout",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.DEFENSE),
                power = 86,
                description = "Unyielding defense through tight technical sectors preventing any passing maneuvers."
            ),
            move2 = CardMove(
                title = "Kannapolis Grit",
                energyCosts = listOf(EnergyType.PACE, EnergyType.PACE),
                power = 84,
                description = "Punching above car weight in race trim to seize critical championship points."
            ),
            weaknessText = "Teammate Duel Heat x 2",
            resistanceText = "Hard Compound Defence -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 85, racecraft = 87, tyreManagement = 85, wetSkill = 84, consistency = 85)
        ),
        TcgCardEntity(
            id = "card_has_87",
            cardNumber = 23,
            name = "Oliver Bearman",
            code = "BEA",
            driverNumber = "#87",
            teamId = "haas",
            teamName = "MoneyGram Haas F1 Team",
            primaryColorHex = "#DEE1E2",
            secondaryColorHex = "#E10600",
            tier = RarityTier.B_TIER,
            ovr = 84,
            role = CardRole.DRIVER,
            powertrain = "Ferrari 067/6",
            debutYear = "2024",
            nationality = "United Kingdom",
            avatarUrl = "https://media.formula1.com/image/upload/c_crop,g_north,w_1080,h_1350/q_auto:best/v1740000001/common/f1/2026/haas/olibea01/2026haasolibea01right.webp",
            verticalBannerText = "BEARMAN",
            move1 = CardMove(
                title = "Jeddah Stand-In Lunge",
                energyCosts = listOf(EnergyType.RACECRAFT, EnergyType.PACE),
                power = 85,
                description = "Spectacular high-speed street bravery diving inside through blind sweeps."
            ),
            move2 = CardMove(
                title = "Banbury Charge",
                energyCosts = listOf(EnergyType.PACE),
                power = 83,
                description = "Aggressive race pace chasing down rivals in the closing laps of the race."
            ),
            weaknessText = "Yellow Flag Zone Caution x 2",
            resistanceText = "Street Agility -15",
            pitCost = 1,
            radarStats = TelemetryRadarStats(qualifyingPace = 86, racecraft = 85, tyreManagement = 82, wetSkill = 83, consistency = 83)
        ),
    )
}
